In [1]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Check the current working directory

import os

os.getcwd()

'C:\\Users\\miked\\Desktop\\Documents\\Data Analysis Projects\\Retail Sales SQL Analysis'

In [3]:
# Set the working directory

os.chdir(r"C:\Users\miked\Desktop\Documents\Data Analysis Projects\Retail Sales SQL Analysis\dataset")

In [4]:
# Load the dataset

mydata = pd.read_csv(r"C:\Users\miked\Desktop\Documents\Data Analysis Projects\Retail Sales SQL Analysis\dataset\online_retail.csv",
                     encoding="latin1")

In [5]:
# Inspect the dataset structure

mydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [6]:
# Display the head of the dataset

mydata.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
# Rename columns for convenience

mydata = mydata.rename(columns={
    'InvoiceNo': 'order_id',
    'StockCode': 'product_code',
    'Description': 'product_name',
    'Quantity': 'quantity',
    'InvoiceDate': 'order_date',
    'UnitPrice': 'unit_price',
    'CustomerID': 'customer_id',
    'Country': 'country'
})

In [8]:
# Convert the date column to the datetime format

mydata['order_date'] = pd.to_datetime(mydata['order_date'])

In [9]:
# Convert the customer ID column to the integer format

mydata['customer_id'] = mydata['customer_id'].astype("Int64")

In [10]:
# Display rows with missing values

mydata[mydata.isna().any(axis=1)]

,order_id,product_code,product_name,quantity,order_date,unit_price,customer_id,country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,<NA>,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,<NA>,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,<NA>,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,<NA>,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,<NA>,United Kingdom
...,...,...,...,...,...,...,...,...
541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,<NA>,United Kingdom
541537,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,<NA>,United Kingdom
541538,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,<NA>,United Kingdom
541539,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,<NA>,United Kingdom
541540,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,<NA>,United Kingdom

In [11]:
# Count missing values in each column

mydata.isna().sum()

order_id             0
product_code         0
product_name      1454
quantity             0
order_date           0
unit_price           0
customer_id     135080
country              0
dtype: int64

In [12]:
# Calculate missing value percentages per column to understand impact of removal

(mydata.isna().sum() / len(mydata) * 100).round(2)

order_id         0.00
product_code     0.00
product_name     0.27
quantity         0.00
order_date       0.00
unit_price       0.00
customer_id     24.93
country          0.00
dtype: float64

In [13]:
# Inspect rows with missing values in product name column

mydata[mydata['product_name'].isna()]

,order_id,product_code,product_name,quantity,order_date,unit_price,customer_id,country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,<NA>,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,<NA>,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,<NA>,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,<NA>,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,<NA>,United Kingdom
...,...,...,...,...,...,...,...,...
535322,581199,84581,NaN,-2,2011-12-07 18:26:00,0.0,<NA>,United Kingdom
535326,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,<NA>,United Kingdom
535332,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,<NA>,United Kingdom
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,<NA>,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,<NA>,United Kingdom

In [14]:
# Drop missing values from product name column

mydata = mydata.dropna(subset=['product_name'])

In [15]:
# Count duplicate entries

mydata.duplicated().sum()

np.int64(5268)

In [16]:
# Inspect duplicate entries to verify whether they are duplicates

mydata[mydata.duplicated(keep=False)].head(20)

,order_id,product_code,product_name,quantity,order_date,unit_price,customer_id,country
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920,United Kingdom

In [17]:
# Remove duplicate entries

mydata = mydata.drop_duplicates()

In [18]:
# Count rows with 0 or negative quantity values

(mydata['quantity'] <= 0).sum()

np.int64(9725)

In [19]:
# Remove rows with invalid quantity values

negative_quantity = mydata[mydata['quantity'] <= 0]

mydata = mydata.drop(negative_quantity.index)

In [20]:
# Count rows with 0 or negative price values

(mydata['unit_price'] <= 0).sum()

np.int64(584)

In [21]:
# Remove rows with invalid price values

negative_price = mydata[mydata['unit_price'] <= 0]

mydata = mydata.drop(negative_price.index)

In [22]:
# Identify cancelled orders

mydata[mydata['order_id'].str.startswith('C', na=False)]

Empty DataFrame
Columns: [order_id, product_code, product_name, quantity, order_date, unit_price, customer_id, country]
Index: []

In [32]:
# Check for remaining alphabetic order IDs

mydata[mydata['order_id'].str.contains('[A-Za-z]', na=False)]

Empty DataFrame
Columns: [order_id, product_code, product_name, quantity, order_date, unit_price, customer_id, country, year, month, revenue]
Index: []

In [31]:
row_remove = mydata[mydata['order_id'].str.contains('[A-Za-z]', na=False)]

mydata = mydata.drop(row_remove.index)

In [23]:
# Create year column of out date column

mydata['year'] = mydata['order_date'].dt.year

In [24]:
# Create month column of out date column

mydata['month'] = mydata['order_date'].dt.month

In [25]:
# Create revenue column combining quantity and price

mydata['revenue'] = mydata['quantity'] * mydata['unit_price']

In [33]:
# Save the cleaned dataset as a csv file

mydata.to_csv("retail_sales_clean.csv", index=False)